updateBranch: true
deleteBranchAfterMerge: true
reportStatus: true

minApprovals:
  COLLABORATOR: 1
maxRequestedChanges:
  NONE: 0
blockingLabels:
- blocked

rules:
- minApprovals:
    OWNER: 1

mergeCommitMessage: "{title} (#{number})"
