updateBranch: true
deleteBranchAfterMerge: true
reportStatus: true

minApprovals:
  COLLABORATOR: 0
maxRequestedChanges:
  NONE: 0
blockingLabels:
- blocked

rules:
- minApprovals:
    OWNER: 2
- requiredLabels:
  - merge

mergeCommitMessage: "{title} (#{number})"
